config/routes.rb
Rails.application.routes.draw do

  resources :users

  root 'static_pages#home'

  get '/secret',    to: 'static_pages#secret'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#about'

  get '/index',     to: 'users#index'
  get '/signup',    to: 'users#new'

  get    '/login',    to: 'sessions#new'
  post   '/login',    to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                   format: { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if log_in?
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def secret
    unless logged_in?
      redirect_to login_path
      flash[:danger] = "Veuillez entrer vos identifiants"
    end
  end

  def about
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Bonjour et bienvenue sur Universe Response"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-fixed-bottom navbar-expand-sm" id="nav-bot">
    <a class="navbar-brand" href="/">Membres du Secret</a>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="#" id="glyphfoot"><span class="glyphicon glyphicon-book"></span> About</a></li>
        <li><a href="#" id="glyphfoot"><span class="glyphicon glyphicon-pencil"></span> Contact</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in? %>
	<nav class="navbar-expand-md navbar-fixed-top navbar-inverse" id="navhead">
		<div class="container-fluid">
			<div class="navbar-header">
		    <a class="navbar-brand" href="/" id="glyphhome">
		      <span class="glyphicon glyphicon-home"></span>
		    </a>
				<a class="navbar-brand" href="/index" id="glyphindex">
        	<b>Liste des Membres du Secret</b>
      		<span class="glyphicon glyphicon-fire"></span>
      	</a>
	   	</div>
			<div class="nav btn-group navbar-expand-md navbar-nav navbar-right" id="glyphprofil">
				<%= link_to current_user, class: "btn btn-lg btn-outline btn-md", id:"glyphprofil" do %>
					<i class="glyphicon glyphicon-user"></i> Profil
				<% end %>
				<%= link_to logout_path, methode: :delete, class: "btn btn-lg btn-outline btn-md", id:"glyphlogout" do %>
					<i class="glyphicon glyphicon-log-out"></i> Log Out
				<% end %>
			</div>
		</div>
	</nav>
<% else %>
	<nav class="navbar-expand-md navbar-fixed-top navbar-inverse" id="navhead">
		<div class="navbar-expand-md navbar-nav navbar-left">
		  <p class="navbar-text">Quelle est La Réponse à la Question sur le Secret de l'Univers</p>
		</div>
		<div class="navbar-brand navbar-right">
			<ul>
				<a class="btn btn-outline-md" href="login" id="gyphlog">
					<span class="glyphicon glyphicon-log-in"></span>
					 <b> Log In </b>
					<span class="glyphicon glyphicon-off"></span>
				</a>
			</ul>
		</div>
	</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UniverseResponde</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>

    <% flash.each do |message_type, message| %>
      <% if message == :danger %>
        <div class = "w3-panel w3-red">
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        </div>
      <%else%>
        <div class = "w3-panel w3-green">
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        </div>
      <% end %>
    <% end %>
      <div class = container>
        <%= yield %>
      </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/static_pages/about.html.erb
<br>
<h1 class="w3-text-orange" class="w3-jumbo" class = w3-section style="text-shadow:1px 1px 0 #444">Au sujet de:</h1>
<br>
<p>Page externe qui sera editer plus tard pour plus de realisme</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>

  <div class="jumbotron" id="jumbologin">
    <h4 style="font-size: 25px">Tu veux toujours connaitre La Réponse<br> à la Question sur le Secret de l'Univers ?</h4>
    <p>Alors clic sur le lien <i>ci-dessous</i> et prepare toi...</p>

  <%= link_to 'Révèle moi le Secret', secret_path, :class => "btn btn-lg btn-primary btn-md", id: "secret", :method => :get %>
  </div>
<%else %>
  <div class="jumbotron" id="jumbologout">
    Si toi aussi tu veux connaitre LA réponse à la Question sur le Secret de l'Univers,<br>
    connecte toi en cliquant sur le bouton <b style="color: yellow"><u><i>Log In</i></u></b>
  </div>

<% end %>

app/views/static_pages/secret.html.erb
<div class="jumbotron" id="jumbosecret">
<h2>On t'a bien eu hein ?</h2>

<iframe width="560" height="315" src="https://fr.wikipedia.org/wiki/42_(nombre)" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if logged_in? %>
  <div class="jumbotron">
    <h2>Editer mon profil</h2>
    <p>Tu peux modifier ton email, ton mot-de-passe</p>
    <br>
    <p> utlisateur n°<%= @user.id %>  -  <%= @user.email %> </p>

  <%= render 'form'%>
    <%= form_for(@user) do |f| %>
      <form>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">Nous ne communiquerons jamais votre adresse email</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
         </div>
         <div class="form-group">
           <label for="exampleInputPassword1">Confirmation</label>
           <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
         </div>
         <button type="submit" class="btn btn-primary">Valider</button>
       </form>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="jumbotron" id="jumbomembres">
  <h2>Liste des Membres du Secret</h2>
<br>
  <% @users.each do |user| %>
    <i style="color: #00FFFF"><%= user.email %></i> <br>
  <% end %>
</div>

app/views/users/new.html.erb
<br>
<h2 class="w3-text-orange" class="w3-jumbo" class = w3-section style="text-shadow:1px 1px 0 #444">Devient un membre du Secret</h2>
<br>
<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <p>Email :</p>
  <%= f.email_field :email, class: 'form-control' %>
<br>
  <p>Mot de passe :</p>
  <%= f.password_field :password, class: 'form-control' %>
<br>
  <p>Confirmation :</p>
  <%= f.password_field :password, class: 'form-control' %>
<br>
  <%= f.submit "Valider", class: "btn btn-success" %>
<% end %>

app/views/users/show.html.erb
<div class="jumbotron" id="jumboshow">
  <h2>Bienvenue Membre du Secret</h2>
<br>
  <h3>Ton identifiant : </h3>
  <i style="color: #00FFFF" "font-size:10px"><%= @user.email %></i>
  <br><br>
   <% if logged_in? && @user == @current_user %>
    <h4> Edite ton profil pour modifier des identifiants et rendre ton profil encore plus secret :</h4>
   <% end %>

  <%= link_to 'Editer mon profil', edit_user_path(@user), :class => "btn btn-lg btn-outline-sm", id: "create" %>
</div>